# Generated by Django 5.2.16 on 2026-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_log',
            field=models.TextField(blank=True, default='Pending dispatch'),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_log',
            field=models.TextField(blank=True, default='Pending dispatch'),
        ),
    ]
